import js from '@eslint/js';
import globals from 'globals';

export default [
  js.configs.recommended,
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...globals.browser,

        activePiece: 'writable',
        hoveredPiece: 'writable',
        dragOffsetX: 'writable',
        dragOffsetY: 'writable',
        isSnapping: 'writable',
        GRID_COLS: 'readonly',
        GRID_ROWS: 'readonly',
        VISUAL_GRID_SIZE: 'readonly',
        puzzleCanvas: 'writable',
        puzzleCtx: 'writable',
        referenceCanvas: 'writable',
        referenceCtx: 'writable',
        tempCanvas: 'writable',
        tempCtx: 'writable',
        imageCache: 'writable',
        processPuzzleData: 'writable',
        loadImage: 'writable',
        initializeCoreCanvases: 'writable',
        resizeCanvases: 'writable',
        updatePiecePixelDimensions: 'writable',
        drawGrid: 'writable',
        drawImageTransformed: 'writable',
        addPiecePathToContext: 'writable',
        renderReference: 'writable',
        renderPuzzle: 'writable',
        drawBorder: 'writable',
        isPointInPiece: 'writable',
        getMousePos: 'writable',
        getRotatedBoundingBoxInPixels: 'writable',
        animateSnap: 'writable',
        renderPiecesToMask: 'writable',
        compareMasks: 'writable',

        isPuzzleSolved: 'writable',
        startTime: 'writable',
        moveCount: 'writable',
        handleHover: 'writable',
        handlePointerDown: 'writable',
        handlePointerMove: 'writable',
        handlePointerUp: 'writable',
        resetGameplayStats: 'writable',
        resetPuzzlePositions: 'writable',
        checkCompletion: 'writable',
        checkCompletionScoped: 'writable',
        playCompletionAnimation: 'writable',
        showModal: 'writable',
        hideModal: 'writable',
        showCompletionModal: 'writable',
        configureCompletionModal: 'writable',
        recordCompletion: 'writable',
        currentPuzzle: 'writable',

        fetchPuzzles: 'writable',
        fetchDailyPuzzle: 'writable',
        fetchScheduledDailies: 'writable',
        fetchPuzzleById: 'writable',
        createPuzzle: 'writable',
        ratePuzzle: 'writable',
        recordPlay: 'writable',
        getPlayedPuzzles: 'writable',
        markPuzzlePlayed: 'writable',
        getUserRating: 'writable',
        saveUserRating: 'writable',
        getCompletedDailies: 'writable',
        isDailyCompleted: 'writable',
        getDailyCompletion: 'writable',
        markDailyCompleted: 'writable',

        renderAll: 'writable',
        renderPuzzleScoped: 'writable',
        rerenderLevelPreviews: 'writable',
        rerenderExplorePreviews: 'writable',
        rerenderGameplayCanvases: 'writable',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],

      'no-redeclare': 'off',

      'no-console': 'off',

      eqeqeq: ['error', 'always'],

      'no-var': 'error',

      'prefer-const': 'off',
    },
  },
  {
    ignores: ['node_modules/**', 'dist/**', 'build/**'],
  },
];
